name: Feature / Change Request
description: Structured feature request for AI-driven implementation
title: "[FEATURE] <Short descriptive title>"
labels: ["type:feature"]
body:
  - type: markdown
    attributes:
      value: |
        ## Before submitting
        - Describe the WHAT and WHY.
        - Do NOT describe the technical implementation unless required.
        - Be explicit and concrete.
        - Avoid vague statements.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem are we solving?
      placeholder: |
        Clear description of the problem.
        Who is affected?
        What is currently broken or missing?
    validations:
      required: true

  - type: textarea
    id: desired_outcome
    attributes:
      label: Desired Outcome
      description: What should exist after this is complete?
      placeholder: |
        Describe observable results.
        What will users be able to do?
    validations:
      required: true

  - type: textarea
    id: constraints
    attributes:
      label: Constraints
      description: Security, performance, architectural, or business constraints
      placeholder: |
        - Must run in Docker
        - Must not introduce new external services
        - Must comply with existing auth system

  - type: dropdown
    id: impact
    attributes:
      label: Impact Level
      options:
        - Low (isolated change)
        - Medium (multiple modules)
        - High (architecture or database impact)
    validations:
      required: true

  - type: dropdown
    id: area
    attributes:
      label: Affected Area
      options:
        - Backend
        - Frontend
        - Database
        - DevOps
        - Security
        - Documentation
        - Other
    validations:
      required: true

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Links, screenshots, logs, diagrams (if applicable)
