name: Task
description: A single, well-scoped piece of work for AI or humans to complete
title: "[TASK] <Short descriptive title>"
labels: ["type:task"]
body:
  - type: markdown
    attributes:
      value: |
        ## Task Rules
        - Keep it small and specific (one outcome).
        - Include definition of done.
        - List deliverables (files, commands, outputs).
        - State constraints and what not to change.

  - type: textarea
    id: objective
    attributes:
      label: Objective
      description: What needs to be accomplished?
      placeholder: |
        One or two sentences describing the task outcome.
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context
      description: Background and why this task exists
      placeholder: |
        Why are we doing this?
        Any relevant links or prior issues/PRs?
    validations:
      required: true

  - type: textarea
    id: scope
    attributes:
      label: Scope
      description: In-scope items (what to do)
      placeholder: |
        - Do X
        - Update Y
        - Add Z
    validations:
      required: true

  - type: textarea
    id: out_of_scope
    attributes:
      label: Out of Scope
      description: Explicitly list what must NOT be changed
      placeholder: |
        - Do not change database schema
        - Do not redesign UI
        - Do not refactor unrelated modules
    validations:
      required: true

  - type: textarea
    id: deliverables
    attributes:
      label: Deliverables
      description: What artifacts should exist when done?
      placeholder: |
        - Files added/changed:
          - path/to/file.ext
        - Commands to run:
          - <command>
        - Output expected:
          - <example output>
    validations:
      required: true

  - type: textarea
    id: definition_of_done
    attributes:
      label: Definition of Done
      description: Clear, testable completion criteria
      placeholder: |
        - [ ] All acceptance checks pass (tests/lint/build)
        - [ ] Docker build succeeds (if applicable)
        - [ ] Docs updated (if applicable)
        - [ ] No secrets committed
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options:
        - P3 (low)
        - P2 (normal)
        - P1 (high)
        - P0 (urgent)
    validations:
      required: true

  - type: dropdown
    id: area
    attributes:
      label: Affected Area
      options:
        - Backend
        - Frontend
        - Database
        - DevOps
        - Security
        - Documentation
        - CI/CD
        - Other
    validations:
      required: true

  - type: textarea
    id: risks
    attributes:
      label: Risks / Considerations
      description: Anything that could break, or needs care
      placeholder: |
        - Potential breaking change for ...
        - Needs migration plan for ...
        - Needs security review because ...

  - type: textarea
    id: ai_execution_hint
    attributes:
      label: AI Execution Hint (Optional)
      description: Help an AI agent start quickly (files/modules/starting point)
      placeholder: |
        Suggested starting files:
        - path/to/file.ts
        Related components:
        - service X, module Y
        Notes:
        - Keep changes minimal, prefer config over code.
